import { User, Class, Subject, Teacher, Student, GradeScale } from "@/types";

export const DEFAULT_USERS: User[] = [
  {
    id: "1",
    username: "admin",
    password: "admin123",
    role: "superadmin",
    name: "អ្នកគ្រប់គ្រង",
    phone: "012345678",
  },
  {
    id: "2",
    username: "teacher1",
    password: "teacher123",
    role: "classteacher",
    name: "លោកគ្រូ ស៊ិន សុផល",
    teacherId: "t1",
    phone: "012345679",
  },
  {
    id: "3",
    username: "teacher2",
    password: "teacher123",
    role: "teacher",
    name: "លោកគ្រូ ចាន់ ដារ៉ា",
    teacherId: "t2",
    phone: "012345680",
  },
  {
    id: "4",
    username: "student1",
    password: "student123",
    role: "student",
    name: "សិស្ស ១",
    studentId: "s1",
  },
];

export const DEFAULT_CLASSES: Class[] = [
  {
    id: "c1",
    name: "ថ្នាក់ទី៧ A",
    grade: 7,
    section: "A",
    year: 2025,
    level: "អនុវិទ្យាល័យ",
    classTeacherId: "t1",
  },
  {
    id: "c2",
    name: "ថ្នាក់ទី៧ B",
    grade: 7,
    section: "B",
    year: 2025,
    level: "អនុវិទ្យាល័យ",
  },
  {
    id: "c3",
    name: "ថ្នាក់ទី១២ A",
    grade: 12,
    section: "A",
    year: 2025,
    level: "វិទ្យាល័យ",
  },
];

export const DEFAULT_SUBJECTS: Subject[] = [
  {
    id: "sub1",
    name: "គណិតវិទ្យា",
    nameEn: "Mathematics",
    level: "both",
    maxScore: { "7": 100, "8": 100, "9": 100, "10": 100, "11": 100, "12": 100 },
  },
  {
    id: "sub2",
    name: "រូបវិទ្យា",
    nameEn: "Physics",
    level: "both",
    maxScore: { "7": 50, "8": 50, "9": 50, "10": 100, "11": 100, "12": 100 },
  },
  {
    id: "sub3",
    name: "គីមីវិទ្យា",
    nameEn: "Chemistry",
    level: "both",
    maxScore: { "7": 50, "8": 50, "9": 50, "10": 100, "11": 100, "12": 100 },
  },
  {
    id: "sub4",
    name: "ភាសាខ្មែរ",
    nameEn: "Khmer",
    level: "both",
    maxScore: { "7": 100, "8": 100, "9": 100, "10": 100, "11": 100, "12": 100 },
  },
  {
    id: "sub5",
    name: "ភាសាអង់គ្លេស",
    nameEn: "English",
    level: "both",
    maxScore: { "7": 100, "8": 100, "9": 100, "10": 100, "11": 100, "12": 100 },
  },
];

export const DEFAULT_TEACHERS: Teacher[] = [
  {
    id: "t1",
    name: "លោកគ្រូ ស៊ិន សុផល",
    phone: "012345679",
    email: "sophal@school.edu.kh",
    subjects: ["sub1", "sub2"],
    classes: ["c1"],
    isClassTeacher: true,
    classTeacherOf: "c1",
  },
  {
    id: "t2",
    name: "លោកគ្រូ ចាន់ ដារ៉ា",
    phone: "012345680",
    email: "dara@school.edu.kh",
    subjects: ["sub4", "sub5"],
    classes: ["c1", "c2"],
    isClassTeacher: false,
  },
];

export const DEFAULT_STUDENTS: Student[] = [
  {
    id: "s1",
    firstName: "សុខ",
    lastName: "ចន្ទា",
    gender: "female",
    dateOfBirth: "2010-05-15",
    classId: "c1",
    phone: "012111222",
    guardianName: "លោក ចន្ទា សុភា",
    guardianPhone: "012111223",
  },
  {
    id: "s2",
    firstName: "វិចិត្រ",
    lastName: "ម៉េង",
    gender: "male",
    dateOfBirth: "2010-08-20",
    classId: "c1",
    phone: "012222333",
    guardianName: "លោក ម៉េង សុវណ្ណ",
    guardianPhone: "012222334",
  },
  {
    id: "s3",
    firstName: "សុភា",
    lastName: "លី",
    gender: "female",
    dateOfBirth: "2010-03-10",
    classId: "c1",
    phone: "012333444",
    guardianName: "លោកស្រី លី ម៉ារី",
    guardianPhone: "012333445",
  },
];

export const GRADE_SCALE: GradeScale[] = [
  { grade: "A", min: 90, max: 100, description: "ល្អបំផុត" },
  { grade: "B", min: 80, max: 89, description: "ល្អ" },
  { grade: "C", min: 70, max: 79, description: "ល្អបង្គួរ" },
  { grade: "D", min: 60, max: 69, description: "មធ្យម" },
  { grade: "E", min: 50, max: 59, description: "ខ្សោយ" },
  { grade: "F", min: 0, max: 49, description: "ធ្លាក់" },
];

// Default Subjects based on Cambodia MoEYS Curriculum
// ក្រសួងអប់រំ យុវជន និងកីឡា

export interface DefaultSubject {
  code: string;
  nameKh: string;
  nameEn: string;
  weeklyHours: number;
  annualHours: number;
  category: "core" | "science" | "social" | "arts" | "technology" | "other";
}

// Grade 7 (ថ្នាក់ទី៧) - Lower Secondary
export const GRADE_7_SUBJECTS: DefaultSubject[] = [
  {
    code: "G7-01",
    nameKh: "អក្សរសាស្ត្រខ្មែរ",
    nameEn: "Khmer Literature",
    weeklyHours: 5,
    annualHours: 160,
    category: "core",
  },
  {
    code: "G7-02",
    nameKh: "គណិតវិទ្យា",
    nameEn: "Mathematics",
    weeklyHours: 6,
    annualHours: 192,
    category: "core",
  },
  {
    code: "G7-03",
    nameKh: "រូបវិទ្យា",
    nameEn: "Physics",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "science",
  },
  {
    code: "G7-04",
    nameKh: "គីមីវិទ្យា",
    nameEn: "Chemistry",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "science",
  },
  {
    code: "G7-05",
    nameKh: "ជីវវិទ្យា",
    nameEn: "Biology",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "science",
  },
  {
    code: "G7-06",
    nameKh: "ផែនដី និងប្រវត្តិវិទ្យា",
    nameEn: "Earth Science & History",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "social",
  },
  {
    code: "G7-07",
    nameKh: "សីលធម៌-ពលរដ្ឋ",
    nameEn: "Morals-Civics",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "social",
  },
  {
    code: "G7-08",
    nameKh: "ភូមិវិទ្យា",
    nameEn: "Geography",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "social",
  },
  {
    code: "G7-09",
    nameKh: "ភាសាបរទេស",
    nameEn: "Foreign Language",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "core",
  },
  {
    code: "G7-10",
    nameKh: "ប្រវត្តិវិទ្យា",
    nameEn: "History",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "social",
  },
  {
    code: "G7-11",
    nameKh: "អប់រំកីឡា",
    nameEn: "Physical Education",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "arts",
  },
  {
    code: "G7-12",
    nameKh: "កម្មវិធីជីវភាពរស់នៅ",
    nameEn: "Life Skills Program",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "other",
  },
  {
    code: "G7-ICT",
    nameKh: "បច្ចេកវិទ្យាព័ត៌មានវិទ្យា (ICT)",
    nameEn: "Information & Communication Technology",
    weeklyHours: 1.5,
    annualHours: 50,
    category: "technology",
  },
];

// Grade 8 (ថ្នាក់ទី៨)
export const GRADE_8_SUBJECTS: DefaultSubject[] = [
  {
    code: "G8-01",
    nameKh: "អក្សរសាស្ត្រខ្មែរ",
    nameEn: "Khmer Literature",
    weeklyHours: 5,
    annualHours: 160,
    category: "core",
  },
  {
    code: "G8-02",
    nameKh: "គណិតវិទ្យា",
    nameEn: "Mathematics",
    weeklyHours: 6,
    annualHours: 192,
    category: "core",
  },
  {
    code: "G8-03",
    nameKh: "រូបវិទ្យា",
    nameEn: "Physics",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "science",
  },
  {
    code: "G8-04",
    nameKh: "គីមីវិទ្យា",
    nameEn: "Chemistry",
    weeklyHours: 3.5,
    annualHours: 112,
    category: "science",
  },
  {
    code: "G8-05",
    nameKh: "ជីវវិទ្យា",
    nameEn: "Biology",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "science",
  },
  {
    code: "G8-06",
    nameKh: "ផែនដី និងប្រវត្តិវិទ្យា",
    nameEn: "Earth Science & History",
    weeklyHours: 3.5,
    annualHours: 112,
    category: "social",
  },
  {
    code: "G8-07",
    nameKh: "សីលធម៌-ពលរដ្ឋ",
    nameEn: "Morals-Civics",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "social",
  },
  {
    code: "G8-08",
    nameKh: "ភូមិវិទ្យា",
    nameEn: "Geography",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "social",
  },
  {
    code: "G8-09",
    nameKh: "ភាសាបរទេស",
    nameEn: "Foreign Language",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "core",
  },
  {
    code: "G8-10",
    nameKh: "ប្រវត្តិវិទ្យា",
    nameEn: "History",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "social",
  },
  {
    code: "G8-11",
    nameKh: "អប់រំកីឡា",
    nameEn: "Physical Education",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "arts",
  },
  {
    code: "G8-ICT",
    nameKh: "បច្ចេកវិទ្យាព័ត៌មានវិទ្យា (ICT)",
    nameEn: "Information & Communication Technology",
    weeklyHours: 1.5,
    annualHours: 50,
    category: "technology",
  },
];

// Grade 9 (ថ្នាក់ទី៩)
export const GRADE_9_SUBJECTS: DefaultSubject[] = [
  {
    code: "G9-01",
    nameKh: "អក្សរសាស្ត្រខ្មែរ",
    nameEn: "Khmer Literature",
    weeklyHours: 5,
    annualHours: 160,
    category: "core",
  },
  {
    code: "G9-02",
    nameKh: "គណិតវិទ្យា",
    nameEn: "Mathematics",
    weeklyHours: 6,
    annualHours: 192,
    category: "core",
  },
  {
    code: "G9-03",
    nameKh: "រូបវិទ្យា",
    nameEn: "Physics",
    weeklyHours: 3.5,
    annualHours: 112,
    category: "science",
  },
  {
    code: "G9-04",
    nameKh: "គីមីវិទ្យា",
    nameEn: "Chemistry",
    weeklyHours: 3.5,
    annualHours: 112,
    category: "science",
  },
  {
    code: "G9-05",
    nameKh: "ជីវវិទ្យា",
    nameEn: "Biology",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "science",
  },
  {
    code: "G9-06",
    nameKh: "ផែនដី និងប្រវត្តិវិទ្យា",
    nameEn: "Earth Science & History",
    weeklyHours: 3.5,
    annualHours: 112,
    category: "social",
  },
  {
    code: "G9-07",
    nameKh: "សីលធម៌-ពលរដ្ឋ",
    nameEn: "Morals-Civics",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "social",
  },
  {
    code: "G9-08",
    nameKh: "ភូមិវិទ្យា",
    nameEn: "Geography",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "social",
  },
  {
    code: "G9-09",
    nameKh: "ភាសាបរទេស",
    nameEn: "Foreign Language",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "core",
  },
  {
    code: "G9-10",
    nameKh: "ប្រវត្តិវិទ្យា",
    nameEn: "History",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "social",
  },
  {
    code: "G9-11",
    nameKh: "អប់រំកីឡា",
    nameEn: "Physical Education",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "arts",
  },
  {
    code: "G9-ICT",
    nameKh: "បច្ចេកវិទ្យាព័ត៌មានវិទ្យា (ICT)",
    nameEn: "Information & Communication Technology",
    weeklyHours: 1.5,
    annualHours: 50,
    category: "technology",
  },
];

// Grade 10 (ថ្នាក់ទី១០) - ផ្នែក​ វិទ្យាសាស្ត្រ
export const GRADE_10_SCIENCE_SUBJECTS: DefaultSubject[] = [
  {
    code: "G10S-01",
    nameKh: "អក្សរសាស្ត្រខ្មែរ",
    nameEn: "Khmer Literature",
    weeklyHours: 5,
    annualHours: 160,
    category: "core",
  },
  {
    code: "G10S-02",
    nameKh: "គណិតវិទ្យា",
    nameEn: "Mathematics",
    weeklyHours: 6,
    annualHours: 192,
    category: "core",
  },
  {
    code: "G10S-03",
    nameKh: "រូបវិទ្យា",
    nameEn: "Physics",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "science",
  },
  {
    code: "G10S-04",
    nameKh: "គីមីវិទ្យា",
    nameEn: "Chemistry",
    weeklyHours: 3.5,
    annualHours: 112,
    category: "science",
  },
  {
    code: "G10S-05",
    nameKh: "ជីវវិទ្យា",
    nameEn: "Biology",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "science",
  },
  {
    code: "G10S-06",
    nameKh: "ផែនដី និងប្រវត្តិវិទ្យា",
    nameEn: "Earth Science & History",
    weeklyHours: 3.5,
    annualHours: 112,
    category: "social",
  },
  {
    code: "G10S-07",
    nameKh: "សីលធម៌-ពលរដ្ឋ",
    nameEn: "Morals-Civics",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "social",
  },
  {
    code: "G10S-08",
    nameKh: "ភូមិវិទ្យា",
    nameEn: "Geography",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "social",
  },
  {
    code: "G10S-09",
    nameKh: "ប្រវត្តិវិទ្យា",
    nameEn: "History",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "social",
  },
  {
    code: "G10S-10",
    nameKh: "ភាសាបរទេស",
    nameEn: "Foreign Language",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "core",
  },
  {
    code: "G10S-11",
    nameKh: "អប់រំកីឡា",
    nameEn: "Physical Education",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "arts",
  },
  {
    code: "G10S-ICT",
    nameKh: "បច្ចេកវិទ្យាព័ត៌មានវិទ្យា (ICT)",
    nameEn: "Information & Communication Technology",
    weeklyHours: 1.5,
    annualHours: 50,
    category: "technology",
  },
];

// Grade 10 (ថ្នាក់ទី១០) - ផ្នែក​ សង្គមវិទ្យា
export const GRADE_10_SOCIAL_SUBJECTS: DefaultSubject[] = [
  {
    code: "G10A-01",
    nameKh: "អក្សរសាស្ត្រខ្មែរ",
    nameEn: "Khmer Literature",
    weeklyHours: 5,
    annualHours: 160,
    category: "core",
  },
  {
    code: "G10A-02",
    nameKh: "គណិតវិទ្យា",
    nameEn: "Mathematics",
    weeklyHours: 6,
    annualHours: 192,
    category: "core",
  },
  {
    code: "G10A-03",
    nameKh: "រូបវិទ្យា",
    nameEn: "Physics",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "science",
  },
  {
    code: "G10A-04",
    nameKh: "គីមីវិទ្យា",
    nameEn: "Chemistry",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "science",
  },
  {
    code: "G10A-05",
    nameKh: "ជីវវិទ្យា",
    nameEn: "Biology",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "science",
  },
  {
    code: "G10A-06",
    nameKh: "ផែនដី និងប្រវត្តិវិទ្យា",
    nameEn: "Earth Science & History",
    weeklyHours: 3.5,
    annualHours: 112,
    category: "social",
  },
  {
    code: "G10A-07",
    nameKh: "សីលធម៌-ពលរដ្ឋ",
    nameEn: "Morals-Civics",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "social",
  },
  {
    code: "G10A-08",
    nameKh: "ភូមិវិទ្យា",
    nameEn: "Geography",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "social",
  },
  {
    code: "G10A-09",
    nameKh: "ប្រវត្តិវិទ្យា",
    nameEn: "History",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "social",
  },
  {
    code: "G10A-10",
    nameKh: "ភាសាបរទេស",
    nameEn: "Foreign Language",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "core",
  },
  {
    code: "G10A-11",
    nameKh: "អប់រំកីឡា",
    nameEn: "Physical Education",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "arts",
  },
  {
    code: "G10A-ICT",
    nameKh: "បច្ចេកវិទ្យាព័ត៌មានវិទ្យា (ICT)",
    nameEn: "Information & Communication Technology",
    weeklyHours: 1.5,
    annualHours: 50,
    category: "technology",
  },
];

// Grade 11 (ថ្នាក់ទី១១) - ផ្នែក​ វិទ្យាសាស្ត្រ
export const GRADE_11_SCIENCE_SUBJECTS: DefaultSubject[] = [
  {
    code: "G11S-01",
    nameKh: "អក្សរសាស្ត្រខ្មែរ",
    nameEn: "Khmer Literature",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "core",
  },
  {
    code: "G11S-02",
    nameKh: "គណិតវិទ្យា",
    nameEn: "Mathematics",
    weeklyHours: 6,
    annualHours: 192,
    category: "core",
  },
  {
    code: "G11S-03",
    nameKh: "រូបវិទ្យា",
    nameEn: "Physics",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "science",
  },
  {
    code: "G11S-04",
    nameKh: "គីមីវិទ្យា",
    nameEn: "Chemistry",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "science",
  },
  {
    code: "G11S-05",
    nameKh: "ជីវវិទ្យា",
    nameEn: "Biology",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "science",
  },
  {
    code: "G11S-06",
    nameKh: "ផែនដី និងប្រវត្តិវិទ្យា",
    nameEn: "Earth Science & History",
    weeklyHours: 3.5,
    annualHours: 112,
    category: "social",
  },
  {
    code: "G11S-07",
    nameKh: "សីលធម៌-ពលរដ្ឋ",
    nameEn: "Morals-Civics",
    nameKh: "អប់រំភូមិ",
    nameEn: "Geography",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "social",
  },
  {
    code: "G11S-08",
    nameKh: "ភូមិវិទ្យា",
    nameEn: "Geography",
    weeklyHours: 4.5,
    annualHours: 96,
    category: "social",
  },
  {
    code: "G11S-09",
    nameKh: "ប្រវត្តិវិទ្យា",
    nameEn: "History",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "social",
  },
  {
    code: "G11S-10",
    nameKh: "ភាសាបរទេស",
    nameEn: "Foreign Language",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "core",
  },
  {
    code: "G11S-11",
    nameKh: "អប់រំកីឡា",
    nameEn: "Physical Education",
    weeklyHours: 4.5,
    annualHours: 80,
    category: "arts",
  },
  {
    code: "G11S-ICT",
    nameKh: "បច្ចេកវិទ្យាព័ត៌មានវិទ្យា (ICT)",
    nameEn: "Information & Communication Technology",
    weeklyHours: 1.5,
    annualHours: 50,
    category: "technology",
  },
];

// Grade 11 (ថ្នាក់ទី១១) - ផ្នែក​ សង្គមវិទ្យា
export const GRADE_11_SOCIAL_SUBJECTS: DefaultSubject[] = [
  {
    code: "G11A-01",
    nameKh: "អក្សរសាស្ត្រខ្មែរ",
    nameEn: "Khmer Literature",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "core",
  },
  {
    code: "G11A-02",
    nameKh: "គណិតវិទ្យា",
    nameEn: "Mathematics",
    weeklyHours: 6,
    annualHours: 192,
    category: "core",
  },
  {
    code: "G11A-03",
    nameKh: "រូបវិទ្យា",
    nameEn: "Physics",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "science",
  },
  {
    code: "G11A-04",
    nameKh: "គីមីវិទ្យា",
    nameEn: "Chemistry",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "science",
  },
  {
    code: "G11A-05",
    nameKh: "ជីវវិទ្យា",
    nameEn: "Biology",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "science",
  },
  {
    code: "G11A-06",
    nameKh: "ផែនដី និងប្រវត្តិវិទ្យា",
    nameEn: "Earth Science & History",
    weeklyHours: 3.5,
    annualHours: 112,
    category: "social",
  },
  {
    code: "G11A-07",
    nameKh: "សីលធម៌-ពលរដ្ឋ",
    nameEn: "Morals-Civics",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "social",
  },
  {
    code: "G11A-08",
    nameKh: "ភូមិវិទ្យា",
    nameEn: "Geography",
    weeklyHours: 4.5,
    annualHours: 96,
    category: "social",
  },
  {
    code: "G11A-09",
    nameKh: "ប្រវត្តិវិទ្យា",
    nameEn: "History",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "social",
  },
  {
    code: "G11A-10",
    nameKh: "ភាសាបរទេស",
    nameEn: "Foreign Language",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "core",
  },
  {
    code: "G11A-11",
    nameKh: "អប់រំកីឡា",
    nameEn: "Physical Education",
    weeklyHours: 4.5,
    annualHours: 80,
    category: "arts",
  },
  {
    code: "G11A-ICT",
    nameKh: "បច្ចេកវិទ្យាព័ត៌មានវិទ្យា (ICT)",
    nameEn: "Information & Communication Technology",
    weeklyHours: 1.5,
    annualHours: 50,
    category: "technology",
  },
];

// Grade 12 (ថ្នាក់ទី១២) - ផ្នែក​ វិទ្យាសាស្ត្រ
export const GRADE_12_SCIENCE_SUBJECTS: DefaultSubject[] = [
  {
    code: "G12S-01",
    nameKh: "អក្សរសាស្ត្រខ្មែរ",
    nameEn: "Khmer Literature",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "core",
  },
  {
    code: "G12S-02",
    nameKh: "គណិតវិទ្យា",
    nameEn: "Mathematics",
    weeklyHours: 6,
    annualHours: 192,
    category: "core",
  },
  {
    code: "G12S-03",
    nameKh: "រូបវិទ្យា",
    nameEn: "Physics",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "science",
  },
  {
    code: "G12S-04",
    nameKh: "គីមីវិទ្យា",
    nameEn: "Chemistry",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "science",
  },
  {
    code: "G12S-05",
    nameKh: "ជីវវិទ្យា",
    nameEn: "Biology",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "science",
  },
  {
    code: "G12S-06",
    nameKh: "ផែនដី និងប្រវត្តិវិទ្យា",
    nameEn: "Earth Science & History",
    weeklyHours: 3.5,
    annualHours: 112,
    category: "social",
  },
  {
    code: "G12S-07",
    nameKh: "សីលធម៌-ពលរដ្ឋ",
    nameEn: "Morals-Civics",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "social",
  },
  {
    code: "G12S-08",
    nameKh: "ភូមិវិទ្យា",
    nameEn: "Geography",
    weeklyHours: 4.5,
    annualHours: 96,
    category: "social",
  },
  {
    code: "G12S-09",
    nameKh: "ប្រវត្តិវិទ្យា",
    nameEn: "History",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "social",
  },
  {
    code: "G12S-10",
    nameKh: "ភាសាបរទេស",
    nameEn: "Foreign Language",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "core",
  },
  {
    code: "G12S-11",
    nameKh: "អប់រំកីឡា",
    nameEn: "Physical Education",
    weeklyHours: 4.5,
    annualHours: 80,
    category: "arts",
  },
  {
    code: "G12S-ICT",
    nameKh: "បច្ចេកវិទ្យាព័ត៌មានវិទ្យា (ICT)",
    nameEn: "Information & Communication Technology",
    weeklyHours: 1.5,
    annualHours: 50,
    category: "technology",
  },
];

// Grade 12 (ថ្នាក់ទី១២) - ផ្នែក​ សង្គមវិទ្យា
export const GRADE_12_SOCIAL_SUBJECTS: DefaultSubject[] = [
  {
    code: "G12A-01",
    nameKh: "អក្សរសាស្ត្រខ្មែរ",
    nameEn: "Khmer Literature",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "core",
  },
  {
    code: "G12A-02",
    nameKh: "គណិតវិទ្យា",
    nameEn: "Mathematics",
    weeklyHours: 6,
    annualHours: 192,
    category: "core",
  },
  {
    code: "G12A-03",
    nameKh: "រូបវិទ្យា",
    nameEn: "Physics",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "science",
  },
  {
    code: "G12A-04",
    nameKh: "គីមីវិទ្យា",
    nameEn: "Chemistry",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "science",
  },
  {
    code: "G12A-05",
    nameKh: "ជីវវិទ្យា",
    nameEn: "Biology",
    weeklyHours: 2.5,
    annualHours: 80,
    category: "science",
  },
  {
    code: "G12A-06",
    nameKh: "ផែនដី និងប្រវត្តិវិទ្យា",
    nameEn: "Earth Science & History",
    weeklyHours: 3.5,
    annualHours: 112,
    category: "social",
  },
  {
    code: "G12A-07",
    nameKh: "សីលធម៌-ពលរដ្ឋ",
    nameEn: "Morals-Civics",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "social",
  },
  {
    code: "G12A-08",
    nameKh: "ភូមិវិទ្យា",
    nameEn: "Geography",
    weeklyHours: 4.5,
    annualHours: 96,
    category: "social",
  },
  {
    code: "G12A-09",
    nameKh: "ប្រវត្តិវិទ្យា",
    nameEn: "History",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "social",
  },
  {
    code: "G12A-10",
    nameKh: "ភាសាបរទេស",
    nameEn: "Foreign Language",
    weeklyHours: 4.5,
    annualHours: 144,
    category: "core",
  },
  {
    code: "G12A-11",
    nameKh: "អប់រំកីឡា",
    nameEn: "Physical Education",
    weeklyHours: 4.5,
    annualHours: 80,
    category: "arts",
  },
  {
    code: "G12A-ICT",
    nameKh: "បច្ចេកវិទ្យាព័ត៌មានវិទ្យា (ICT)",
    nameEn: "Information & Communication Technology",
    weeklyHours: 1.5,
    annualHours: 50,
    category: "technology",
  },
];

export const DEFAULT_SUBJECTS_BY_GRADE: Record<string, DefaultSubject[]> = {
  "7": GRADE_7_SUBJECTS,
  "8": GRADE_8_SUBJECTS,
  "9": GRADE_9_SUBJECTS,
  "10-science": GRADE_10_SCIENCE_SUBJECTS,
  "10-social": GRADE_10_SOCIAL_SUBJECTS,
  "11-science": GRADE_11_SCIENCE_SUBJECTS,
  "11-social": GRADE_11_SOCIAL_SUBJECTS,
  "12-science": GRADE_12_SCIENCE_SUBJECTS,
  "12-social": GRADE_12_SOCIAL_SUBJECTS,
};

// Helper function to get subjects by grade
export function getDefaultSubjectsByGrade(
  grade: string,
  track?: "science" | "social"
): DefaultSubject[] {
  if (grade === "10" || grade === "11" || grade === "12") {
    const key = `${grade}-${track || "science"}`;
    return DEFAULT_SUBJECTS_BY_GRADE[key] || [];
  }
  return DEFAULT_SUBJECTS_BY_GRADE[grade] || [];
}

// Get all unique subjects (for filtering/searching)
export function getAllUniqueSubjects(): DefaultSubject[] {
  const allSubjects: DefaultSubject[] = [];
  const seen = new Set<string>();

  Object.values(DEFAULT_SUBJECTS_BY_GRADE).forEach((subjects) => {
    subjects.forEach((subject) => {
      if (!seen.has(subject.nameEn)) {
        seen.add(subject.nameEn);
        allSubjects.push(subject);
      }
    });
  });

  return allSubjects;
}
